[2024-05-01T16:24:18.387+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T16:24:18.428+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-05-01T16:24:09.436956+00:00 [queued]>
[2024-05-01T16:24:18.436+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-05-01T16:24:09.436956+00:00 [queued]>
[2024-05-01T16:24:18.437+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T16:24:18.450+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_wikipedia_data> on 2024-05-01 16:24:09.436956+00:00
[2024-05-01T16:24:18.455+0000] {standard_task_runner.py:63} INFO - Started process 3958 to run task
[2024-05-01T16:24:18.458+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data', 'manual__2024-05-01T16:24:09.436956+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpp0ww43u_']
[2024-05-01T16:24:18.461+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask transform_wikipedia_data
[2024-05-01T16:24:18.521+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-05-01T16:24:09.436956+00:00 [running]> on host ab8381b78bd9
[2024-05-01T16:24:18.729+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Minh Tran' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T16:24:09.436956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T16:24:09.436956+00:00'
[2024-05-01T16:24:18.730+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T16:39:42.749+0000] {logging_mixin.py:188} WARNING - /opt/***/pipelines/wikipedia_pipeline.py:110 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-05-01T16:39:42.786+0000] {python.py:237} INFO - Done. Returned value was: OK
[2024-05-01T16:39:42.787+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T16:39:42.809+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=wikipedia_flow, task_id=transform_wikipedia_data, execution_date=20240501T162409, start_date=20240501T162418, end_date=20240501T163942
[2024-05-01T16:39:42.860+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-01T16:39:42.959+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-01T16:39:42.960+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
