[2024-05-03T15:56:58.742+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T15:56:58.770+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-05-03T15:56:50.916826+00:00 [queued]>
[2024-05-03T15:56:58.776+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-05-03T15:56:50.916826+00:00 [queued]>
[2024-05-03T15:56:58.777+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-03T15:56:58.788+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_wikipedia_data> on 2024-05-03 15:56:50.916826+00:00
[2024-05-03T15:56:58.791+0000] {standard_task_runner.py:63} INFO - Started process 19184 to run task
[2024-05-03T15:56:58.793+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data', 'manual__2024-05-03T15:56:50.916826+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpltsan8x0']
[2024-05-03T15:56:58.794+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask transform_wikipedia_data
[2024-05-03T15:56:58.838+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-05-03T15:56:50.916826+00:00 [running]> on host ac73955389ba
[2024-05-03T15:56:58.997+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Minh Tran' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T15:56:50.916826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-03T15:56:50.916826+00:00'
[2024-05-03T15:56:58.998+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T16:10:58.138+0000] {logging_mixin.py:188} WARNING - /opt/***/pipelines/wikipedia_pipeline.py:110 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-05-03T16:10:58.170+0000] {python.py:237} INFO - Done. Returned value was: OK
[2024-05-03T16:10:58.170+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T16:10:58.194+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=wikipedia_flow, task_id=transform_wikipedia_data, execution_date=20240503T155650, start_date=20240503T155658, end_date=20240503T161058
[2024-05-03T16:10:58.231+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-03T16:10:58.329+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-03T16:10:58.335+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
