[2024-05-01T16:44:33.940+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T16:44:33.967+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-05-01T16:44:25.411038+00:00 [queued]>
[2024-05-01T16:44:33.975+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-05-01T16:44:25.411038+00:00 [queued]>
[2024-05-01T16:44:33.975+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T16:44:33.985+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_wikipedia_data> on 2024-05-01 16:44:25.411038+00:00
[2024-05-01T16:44:33.990+0000] {standard_task_runner.py:63} INFO - Started process 4339 to run task
[2024-05-01T16:44:33.992+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data', 'manual__2024-05-01T16:44:25.411038+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmppp1v0sxm']
[2024-05-01T16:44:33.994+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask transform_wikipedia_data
[2024-05-01T16:44:34.039+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-05-01T16:44:25.411038+00:00 [running]> on host ab8381b78bd9
[2024-05-01T16:44:34.203+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Minh Tran' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T16:44:25.411038+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T16:44:25.411038+00:00'
[2024-05-01T16:44:34.204+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T17:00:24.026+0000] {logging_mixin.py:188} WARNING - /opt/***/pipelines/wikipedia_pipeline.py:110 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-05-01T17:00:24.061+0000] {python.py:237} INFO - Done. Returned value was: OK
[2024-05-01T17:00:24.061+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T17:00:24.084+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=wikipedia_flow, task_id=transform_wikipedia_data, execution_date=20240501T164425, start_date=20240501T164433, end_date=20240501T170024
[2024-05-01T17:00:24.138+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-01T17:00:24.233+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-01T17:00:24.240+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
